spring:
  datasource:
    url: jdbc:mysql://143.110.182.202:3306/opinion_db
    username: opinion_dev
    password: opinion
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: opinion.techsupp@gmail.com
    password: xtdk zfst utei mtjj
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  data:
    redis:
      host: 143.110.182.202
      port: 6379
  cache:
    type: redis
    redis:
      use-key-prefix: true
      key-prefix: "galina:"
server:
  port: 8888

app:
  jwtSecret: EhOW5DsaD9/Zw/0k68ulRgTGNEOjToLE8jcfQtDGUK8YvfQpsIXma9uP16mW0Rjh
  jwtExpirationInMs: 36000000

cloudinary:
  cloud_name: dz296z7yk
  api_key: 331978117334288
  api_secret: FPj3U4WzuMAEW-CdGUECvs_HZ4k
caching:
  spring:
#    articlesTTL: 86400000 # 24 hours
    articlesTTL: 3600000 #1 hour

client-application:
  host: 143.110.182.202
  route:
    password:
      reset: "/reset-password"


