spring:
  datasource:
    url: jdbc:mysql://localhost:3306/opinion_db
    username: opinion_dev
    password: opinion
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: opinion.techsupp@gmail.com
    password: ifeq ffqc cdvz lvog
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

server:
  port: 8812

app:
  jwtSecret: EhOW5DsaD9/Zw/0k68ulRgTGNEOjToLE8jcfQtDGUK8YvfQpsIXma9uP16mW0Rjh
  jwtExpirationInMs: 36000000